In [38]:
#https://stackabuse.com/introduction-to-neural-networks-with-scikit-learn/

In [39]:
import sklearn
import pandas as pd
import numpy

In [44]:
data = pd.read_csv("C://Users/583175/.jupyter/iris.data.txt")
data.columns = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

In [48]:
data

sepal-length  sepal-width  petal-length  petal-width           Class
0             4.9          3.0           1.4          0.2     Iris-setosa
1             4.7          3.2           1.3          0.2     Iris-setosa
2             4.6          3.1           1.5          0.2     Iris-setosa
3             5.0          3.6           1.4          0.2     Iris-setosa
4             5.4          3.9           1.7          0.4     Iris-setosa
5             4.6          3.4           1.4          0.3     Iris-setosa
6             5.0          3.4           1.5          0.2     Iris-setosa
7             4.4          2.9           1.4          0.2     Iris-setosa
8             4.9          3.1           1.5          0.1     Iris-setosa
9             5.4          3.7           1.5          0.2     Iris-setosa
10            4.8          3.4           1.6          0.2     Iris-setosa
11            4.8          3.0           1.4          0.1     Iris-setosa
12            4.3          3.0           1.1          0.1     Iris-setosa
13            5.8          4.0           1.2          0.2     Iris-setosa
14            5.7          4.4           1.5          0.4     Iris-setosa
15            5.4          3.9           1.3          0.4     Iris-setosa
16            5.1          3.5           1.4          0.3     Iris-setosa
17            5.7          3.8           1.7          0.3     Iris-setosa
18            5.1          3.8           1.5          0.3     Iris-setosa
19            5.4          3.4           1.7          0.2     Iris-setosa
20            5.1          3.7           1.5          0.4     Iris-setosa
21            4.6          3.6           1.0          0.2     Iris-setosa
22            5.1          3.3           1.7          0.5     Iris-setosa
23            4.8          3.4           1.9          0.2     Iris-setosa
24            5.0          3.0           1.6          0.2     Iris-setosa
25            5.0          3.4           1.6          0.4     Iris-setosa
26            5.2          3.5           1.5          0.2     Iris-setosa
27            5.2          3.4           1.4          0.2     Iris-setosa
28            4.7          3.2           1.6          0.2     Iris-setosa
29            4.8          3.1           1.6          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
119           6.9          3.2           5.7          2.3  Iris-virginica
120           5.6          2.8           4.9          2.0  Iris-virginica
121           7.7          2.8           6.7          2.0  Iris-virginica
122           6.3          2.7           4.9          1.8  Iris-virginica
123           6.7          3.3           5.7          2.1  Iris-virginica
124           7.2          3.2           6.0          1.8  Iris-virginica
125           6.2          2.8           4.8          1.8  Iris-virginica
126           6.1          3.0           4.9          1.8  Iris-virginica
127           6.4          2.8           5.6          2.1  Iris-virginica
128           7.2          3.0           5.8          1.6  Iris-virginica
129           7.4          2.8           6.1          1.9  Iris-virginica
130           7.9          3.8           6.4          2.0  Iris-virginica
131           6.4          2.8           5.6          2.2  Iris-virginica
132           6.3          2.8           5.1          1.5  Iris-virginica
133           6.1          2.6           5.6          1.4  Iris-virginica
134           7.7          3.0           6.1          2.3  Iris-virginica
135           6.3          3.4           5.6          2.4  Iris-virginica
136           6.4          3.1           5.5          1.8  Iris-virginica
137           6.0          3.0           4.8          1.8  Iris-virginica
138           6.9          3.1           5.4          2.1  Iris-virginica
139           6.7          3.1           5.6          2.4  Iris-virginica
140           6.9          3.1           5.1          2.3  Iris-virginica
141      

In [50]:
x = data.iloc[:, 0:4]

# Assign data from first fifth columns to y variable
y = data['Class']
print(x)
print(y)

     sepal-length  sepal-width  petal-length  petal-width
0             4.9          3.0           1.4          0.2
1             4.7          3.2           1.3          0.2
2             4.6          3.1           1.5          0.2
3             5.0          3.6           1.4          0.2
4             5.4          3.9           1.7          0.4
5             4.6          3.4           1.4          0.3
6             5.0          3.4           1.5          0.2
7             4.4          2.9           1.4          0.2
8             4.9          3.1           1.5          0.1
9             5.4          3.7           1.5          0.2
10            4.8          3.4           1.6          0.2
11            4.8          3.0           1.4          0.1
12            4.3          3.0           1.1          0.1
13            5.8          4.0           1.2          0.2
14            5.7          4.4           1.5          0.4
15            5.4          3.9           1.3          0.4
16            

In [53]:
y.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [64]:
from sklearn import preprocessing
labelencoder = preprocessing.LabelEncoder()

y = labelencoder.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [65]:
from sklearn.model_selection import train_test_split

In [67]:
train, test, train_labels, test_labels = train_test_split(x, y, test_size=0.20, random_state=42)

In [68]:
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
scaler.fit(train)

train = scaler.transform(train)  
test = scaler.transform(test) 

In [71]:
from sklearn.neural_network import MLPClassifier  
mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)  
mlp.fit(train, train_labels.ravel())

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(10, 10, 10), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [73]:
predictions = mlp.predict(test)
predictions

array([1, 0, 2, 1, 2, 0, 1, 2, 1, 2, 2, 0, 0, 0, 0, 1, 2, 2, 1, 2, 0, 2, 0,
       2, 2, 2, 2, 2, 0, 0], dtype=int64)

In [76]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score 
print(confusion_matrix(test_labels, predictions))  
print(classification_report(test_labels, predictions))
print(accuracy_score(test_labels, predictions))

[[10  0  0]
 [ 0  6  3]
 [ 0  0 11]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        10
          1       1.00      0.67      0.80         9
          2       0.79      1.00      0.88        11

avg / total       0.92      0.90      0.90        30

0.9
